"""
Django settings for lvndry project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import logging
from logging.handlers import RotatingFileHandler
from dotenv import load_dotenv
load_dotenv()


BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "asdfffffffffasdfasdfl2314kjjkff;;lik"

DEBUG = False

ALLOWED_HOSTS = ['luvndry.ir', 'www.luvndry.ir']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'ckeditor',
    'ckeditor_uploader',
    'Customers',
    'Items',
    'Orders',
    'conf',
    'CMS',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'lvndry.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "front" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lvndry.wsgi.application'



import os

import pymysql
pymysql.install_as_MySQLdb()


DATABASES = {
    'default': {
        'ENGINE':'django.db.backends.mysql',
        'NAME': 'tjgwciyd_luvndry_db' ,
        'USER': 'tjgwciyd_hamid20dey' ,
        'PASSWORD': 'hamid20dey' ,
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'"
        },
    }
}




X_FRAME_OPTIONS = 'SAMEORIGIN'





AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [BASE_DIR / "front" / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CKEDITOR_UPLOAD_PATH = "uploads/"



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


BASE_DIR = Path(__file__).resolve().parent.parent

LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '[{asctime}] [{levelname}] {name}:{lineno} — {message}',
            'style': '{',
        },
    },

    'handlers': {
        'main_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django_app.log'),
            'formatter': 'verbose',
            'maxBytes': 30 * 1024 * 1024,
            'backupCount': 10,
            'encoding': 'utf-8',
        },

        'cms_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'cms.log'),
            'formatter': 'verbose',
            'maxBytes': 30 * 1024 * 1024,
            'backupCount': 10,
            'encoding': 'utf-8',
        },
        'customers_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'customers.log'),
            'formatter': 'verbose',
            'maxBytes': 30 * 1024 * 1024,
            'backupCount': 10,
            'encoding': 'utf-8',
        },
        'items_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'items.log'),
            'formatter': 'verbose',
            'maxBytes': 30 * 1024 * 1024,
            'backupCount': 10,
            'encoding': 'utf-8',
        },
        'orders_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'orders.log'),
            'formatter': 'verbose',
            'maxBytes': 30 * 1024 * 1024,
            'backupCount': 10,
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['main_file'],
        'level': 'INFO',
    },

    'loggers': {
        'django': {
            'handlers': [], 
            'level': 'INFO',
            'propagate': True,
        },
        'cms': {
            'handlers': ['cms_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'customers': {
            'handlers': ['customers_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'items': {
            'handlers': ['items_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'orders': {
            'handlers': ['orders_file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'